#!/usr/bin/env bash
# install load balancer

echo -e "Updating and doing some minor checks...\n"

function install() {
        command -v "$1" &> /dev/null

        #shellcheck disable=SC2181
        if [ $? -ne 0 ]; then
                echo -e "       Installing: $1\n"
                sudo apt-get update -y -qq && \
                        sudo apt-get install -y "$1" -qq
                echo -e "\n"
        else
                echo -e "       ${1} is already installed.\n"
        fi
}

install haproxy #install haproxy

echo -e "\nSetting up some minor stuff.\n"

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend msebelejnr-frontend
    bind *:80
    default_backend msebelejnr-backend

backend msebelejnr-backend
    balance roundrobin
    server 422486-web-01 18.210.20.15:80 check
    server 422486-web-02 3.83.238.20:80 check
"

# Write server_config to haproxy.cfg
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

echo "configured - Roundrobin On web-01 & web-02"

# Start or restart haproxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi
