#!/bin/env bash

# Stop Nginx service
service nginx stop

# Change ownership of Nginx files to nginx user
chown -R nginx:nginx /etc/nginx /var/log/nginx

# Change Nginx process to run as nginx user
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# Restart Nginx service
service nginx start

# Verify Nginx is running as nginx user
pgrep -u nginx nginx

# Verify Nginx is listening on port 8080
nc -z 0 8080


